### ISSUE TITLE
No migrations showing up after install

### ISSUE THREAD

**Issue by joelion** [ctxis/django-admin-view-permission#11]
I pip installed version `f170c3c` and added `'admin_view_permission',` to `INSTALLED_APPS`, but no new migrations are showing up when I run `showmigrations` or `migrate`. To confirm `admin_view_permission` is being loaded, when I add a typo to the name and run `showmigrations` I get an ImportError, as expected. Is there anything I need to do besides adding to `INSTALLED_APPS` and running `migrate`? 

django 1.9.2
python 3.4.4

**Comment by lefterisnik** [comment]
Hi @joelion,

Yes, you need only to add it to `INSTALLED_APPS` and run `migrate`. The package doesn't contain any actual migrations. It uses `migrate` to create the new permissions on the db (like django does for the default permissions).  

I hope this to answer your question.

Thanks,
Lefteris

**Comment by joelion** [comment]
Got it. I was expecting more fanfare, so I didn't even check the admin page to see if it changed. 

However, now as soon as I enable the plugin and go to admin, I don't have _any_ permissions to see or do anything on the admin site. 
![image](https://cloud.githubusercontent.com/assets/5199709/22549111/ad547834-e984-11e6-8274-71c858cd936e.png)

My account is a superuser (screenshot taken when plugin isn't enabled) 
![image](https://cloud.githubusercontent.com/assets/5199709/22549122/bee121ce-e984-11e6-997d-5367ee491241.png)

**Comment by lefterisnik** [comment]
Hi @joelion,

This not normal. Superuser should have the ability to see all the models. 

Did you add the 'admin_view_permission' at the top on the INSTALLED_APPS? To see what's going wrong you can run `python manage.py shell` and execute the following commands:

```
from django.contrib.auth.models import User
u = User.objects.get(username=<your username>)
u.user_permissions.all()
u.groups.all()
```

Both command should return empty querysets. Otherwise set them to None and try to login as superuser again.

Thanks,
Lefreris

**Comment by joelion** [comment]
Great, got it. I didn't realize that the order in INSTALLED_APPS mattered. Putting admin_view_permission at the top got everything working as expected. 

Really surprised this feature it's built-in functionality... thanks
