### ISSUE TITLE
[Problem] Doesn't display choices from related table

### ISSUE THREAD

**Issue by mykljohn** [ctxis/django-admin-view-permission#2]
Looks great, but when I call to a related model, it only shows the code:
`Vocabulary in General                [u'10']`

and it doesn't expand the inline Questionaire.  
Installed:
Django 1.8.6, 
Python 2.7, 
Grappelli 2.7.1, 
ckeditor 4.4.8 - used for Questionnaire,
MultiSelectField 0.1.3 - used for Summary

Here's my admin.py:
```
class EvaluationAdmin(admin.ModelAdmin):
    fieldsets = [
        ('Scheduling Info',    {'fields': [('candidate'), ('user', ), ('status'), ('source'), ('sourcename')]}),
        ("Questionnaire", {"classes": ("placeholder evaluationresponse_set-group",), "fields" : ()}),
        ("Feedback", {"classes": ("placeholder evaluationscore-group",), "fields" : ()}),
        ('Comments', {'fields': [('comments')]}),
        ('Summary', {'fields': [('grammar', ), ('conversation'), ('pronunciation'), ('confidence'), ('level')]}),
    ]
```
Here are my models:
```
class Evaluation(models.Model):
    xRATING = (
       ("E", "Excellent "),
       ("VG", "Very Good "),
       ("G", "Good "),
       ("R", "Regular "),
       ("N", "Needs Improvement "),
       ("P", "Poor "),
    )
    grammar= models.CharField(choices=xRATING, max_length=30, blank=True, null=True, verbose_name='Applied Grammar')

class EvaluationScore(models.Model):
    xSCOREMSGS1 = (
        (10, "Excellent amount of vocabulary."),
        (11, "Good amount of vocabulary.  Always room for improvement."),
        (12, "Needs to acquire more vocabulary to express ideas better."),
        (13, "Used some false cognates."),
        (14, "Does not have sufficient vocabulary to express ideas; used several false cognates or invented words, used Spanish."),
    )
   vocabulary_general= MultiSelectField(choices=xSCOREMSGS1, max_length=30, blank=True, null=True, verbose_name='Vocabulary in General')
```
And here's my form:

```
class EvaluationResponseform(forms.ModelForm):
    response = forms.CharField(widget=CKEditorWidget(),
    	label=mark_safe("<normal><br/><br/><br/>Are you currently living in a house or in an apartment?"), required=False,)

    class Meta:
        model = EvaluationResponse
        fields = ('response',)
```

**Comment by lefterisnik** [comment]
Hi @mykljohn,

Thanks for reporting the issue. 

I looked the MultiSelectField and as I noticed, it doesn't contain any widget when this field is readonly.

For example, if you add in the `admin.py` at the ModelAdmin of the EvaluationScore the attribute

`readonly_fields = ('vocabulary_general',)`

again the default admin app, without the admin_view_permission app shows this field weird:

`Vocabulary in General [u'10']`

Maybe, when this field is readonly calls some method for CharField which inherits and return a simple text. I think, a possible solution is to override the MultiSelectField and find the method which called when this field is readonly.

Please, let me know for any comments.
