### ISSUE TITLE
Support alternative fields format

### ISSUE THREAD

**Issue by kapucko** [ctxis/django-admin-view-permission#20]
Hi,

I have just noticed that fields attribute may look like this: ((attr1, attr2), attr3) according to https://docs.djangoproject.com/en/1.11/ref/contrib/admin/#django.contrib.admin.ModelAdmin.fields .
On the other hand, readonly_fields doesn't support such format and those fields in tuples won't be displayed. I'll provide a PR for this (spent quite a lot of time debugging it). I hope that it'll be clear what's going on there.

**Comment by lefterisnik** [comment]
Hi @kapucko,

Thank you for the pull request. I will have a look asap
