### ISSUE TITLE
Problem when get_readonly_fields() is used

### ISSUE THREAD

**Issue by escribis** [ctxis/django-admin-view-permission#23]
django-admin-view-permission is really cool :-)

Something is strange: with read_only -> OK but with get_readonly_fields() -> KO

Here is the detail. With just a view permission on a Model.  

(1) when I use the attribute 'readonly_fields' as below

```
class MyModelAdmin(model.Admin):
    ...
    readonly_fields = (a,b)
```
The result in the admin "change view"  : all the attributes are displayed in readonly (expected).  

(2)  when I use instead get_readonly_fields(self, request, obj=None)
```
class MyModelAdmin(model.Admin):
    ...
    def get_readonly_fields(self, request, obj=None):
        return (a,b)

```
--> all the fields that are in this list (here a,b) are readonly (as expected), but all other fields are read/write (this is unexpected). The rest is ok, no button save, etc.

I'm missing something ?
Thks

**Comment by lefterisnik** [comment]
Hi @escribis,

Instead of returning directly the tuple of the fields, you could do something like this:

```
def get_readonly_fields(self, request, obj=None):
      # the following command will calculate the readonly_fieds based on the admin_view_permission 
      # package (eg: if the user has view permission it will return all the fields otherwise it will return
      # those fields based on the django `ModelAdmin` or you custom class)  
      readonly_fields = super(MyModelAdmin, self).get_readonly_fields(request, obj)  
      
      # Here you can put your code and change the readonly_fields based on extra logic or extra permissions

      return readonly_fields
```

Thanks,
Lefteris

**Comment by escribis** [comment]
Thnks ! Works like a charm :+1:
