### ISSUE TITLE
Change permission still required to delete models

### ISSUE THREAD

**Issue by ciarancourtney** [ctxis/django-admin-view-permission#24]
Is it expected behaviour that if a User has view and delete permissions, that they won't be able to delete? i.e. there is still a predicate that a user requires change to add or delete models?

**Comment by ciarancourtney** [comment]
Excuse me, I see that it is possible to delete an instance from its change page, but delete actions are hidden from the changelist page, so to correct my original question, is this expected behaviour?

**Comment by lefterisnik** [comment]
Hi @ciarancourtney,

This seems like a bug. I will have a look asap.

Thanks,
Lefteris
