### ISSUE TITLE
MultiValueDictKeyError

### ISSUE THREAD

**Issue by satyagrahaa** [ctxis/django-admin-view-permission#26]
Hi there,

I'm receiving MultiValueDictKeyError from here: admin_view_permission/admin.py in change_view at line 231.

Your help is much appreciated.

**Comment by lefterisnik** [comment]
Hi @satyagrahaa, which version do you use?

**Comment by lefterisnik** [comment]
Hi @satyagrahaa, I think the problem is caused because of using an old version of the package. If you try to upgrade it to the latest version I think your problem will be solved.
