### ISSUE TITLE
Inlines Change Permission

### ISSUE THREAD

**Issue by geekashu** [ctxis/django-admin-view-permission#3]
Hi,

Very helpful package.I have a issue here. I enabled view permission for my custom user model. This model is also connected to profile model via one to one relation. Now if i assign a user view permission of custom user model and change permission of profile model, my admin still shows the profile inline as readonly.

Is this something that can be taken care of in this great package?

**Comment by lefterisnik** [comment]
Hi @geekashu,

Thanks for reporting the issue.

The package originally designed to have this behavior. The inline models inherited the permission from the parent. For that reason, if the parent model had view permission all the inline models respected that permission. 

But right now, this behavior changed. The package respects each model permission.

I will push a new version 0.3
