### ISSUE TITLE
Determine if current admin form is view-only in __init__

### ISSUE THREAD

**Issue by ciarancourtney** [ctxis/django-admin-view-permission#30]
Apart from passing the request into the form and checking user permissions, is there a way to determine that the current changepage is view-only?

**Comment by lefterisnik** [comment]
Hi @ciarancourtney, I can't find an easy way to determine this. Maybe, you could try the `_has_change_only_permission` method. I don't know exactly your case but you could have something like this:

```
def get_form(self, request, obj=None, **kwargs):
    form = super().get_form(request, obj, **kwargs)
    if self._has_change_only_permission(request, obj):
        return <the_form_that_you_want>

    return form
```

**Comment by ciarancourtney** [comment]
Does `_has_change_only_permission()` return False if user has view and change? If so I think I'd use has_change_permission(), as its typical to layer permission in order of privilege i.e. a view-only user has view perm, a change user has view and change, a full user has view, change, add delete and so on

**Comment by lefterisnik** [comment]
The `_has_change_only_permission` runs underneath the super `has_change_permission`. So, if the user has change permission it will return True otherwise it will return False. In general if you want determine that the view is view-only you need to have something like this:

```
if not self._has_change_only_permission(request, obj) and self.has_view_permission(request, obj)
```
