### ISSUE TITLE
Auth User password hash is shown in default UserAdmin

### ISSUE THREAD

**Issue by ciarancourtney** [ctxis/django-admin-view-permission#32]
Maybe add a failsafe to prevent this? I think its censored somehow in the normal change form

**Comment by lefterisnik** [comment]
Hey @ciarancourtney,

I am very close to finish this ticket. I managed to show the default widget (which hides the hash) on the user's password, but still the user can edit the password. I will continue working on this.

I wish you happy New Year,

Thanks,
Lefteris
