### ISSUE TITLE
users and groups admin site

### ISSUE THREAD

**Issue by matiasAS** [ctxis/django-admin-view-permission#34]
Hello,
I have the following problem: I installed this package with django version 1.11.5 and after adding it to the INSTALLED_APPS array on the admin site I do not see users or groups, could you please help me to solve this problem?

**Comment by lefterisnik** [comment]
Hi @matiasAS,

Sorry for the late response. After adding the app into the INSTALLED_APPS you need to `python manage.py migrate` to create the permissions for the models. Then you can edit the users/groups you want and assign them the permissions you want

Thanks,
Lefteris
