### ISSUE TITLE
You don't have permission to edit anything at the admin page

### ISSUE THREAD

**Issue by weasteam** [ctxis/django-admin-view-permission#35]
After I installed the app, I lost my permission in viewing admin page. I am a superuser.

`You don't have permission to edit anything.`

Any idea on how to resolve it?

**Comment by lefterisnik** [comment]
Hi @weasteam,

Did you run `migrate`?

**Comment by weasteam** [comment]
@lefterisnik, Yes, I did.

When I removed the app, I got permission back.

**Comment by codeZeilen** [comment]
@lefterisnik: just a heads up that I see the same effect. Neither running makemigrations nor migrate finds anything to migrate.

**Comment by lefterisnik** [comment]
Hi guys,

Which Django version do you use, in order to reproduce it?

**Comment by codeZeilen** [comment]
Hey,

thanks for looking into this. I am using Django 1.11 with Python 3.4.2.

**Comment by weasteam** [comment]
For me, Django version 1.10.5, Python 3.5.2

**Comment by Michaeljczhang** [comment]
I had the same issue. 
You need to place the `admin_view_permission` before `django.contrib.admin` in settings.py

**Comment by cheng10** [comment]
I think a little clarification in the README would be nice:

> You need to place the admin_view_permission before django.contrib.admin in settings.py

**Comment by lefterisnik** [comment]
Hi all, 

I've just updated the README.rst file as you suggested. Thanks for you feedback.
