### ISSUE TITLE
Django 2.0 support

### ISSUE THREAD

**Issue by sebatyler** [ctxis/django-admin-view-permission#37]
I want to use this app to my django 2.0 project.

**Comment by DEKHTIARJonathan** [comment]
@ctxis any time frame for a new release supporting Django 2.0?

Thanks mate

**Comment by lefterisnik** [comment]
It is planned for this weekend. Probably sooner.

Thanks,
Lefteris

**Comment by DEKHTIARJonathan** [comment]
Awesome! Thanks mate

**Comment by DEKHTIARJonathan** [comment]
@lefterisnik : Do you have any problem where I could help you ?

All the best and merry christmas

Jonathan

**Comment by lefterisnik** [comment]
Merry Christmas all,

Thanks @DEKHTIARJonathan, some tests are failing because something has changed on Django 2.0 on the request object, Arghh. I am looking on that.

Thanks,
Lefteris

**Comment by lefterisnik** [comment]
Hi all,

I've just pushed the [new release](https://pypi.python.org/pypi/django-admin-view-permission/1.2) which supports Django 2.0.

Sorry for the delay.

@DEKHTIARJonathan the issue wasn't the request object but the `MIDDLEWARE` attribute on settings.py.

Thanks,
Lefteris
