### ISSUE TITLE
Deleting object using Action menu raises KeyError: 'cl'

### ISSUE THREAD

**Issue by ciarancourtney** [ctxis/django-admin-view-permission#39]
If user has view but not change perm, deleting using the action menu will raise a KeyError here https://github.com/ctxis/django-admin-view-permission/blob/master/admin_view_permission/admin.py#L300

Affects Django 1.11.8

**Comment by lefterisnik** [comment]
HI @ciarancourtney,

I will publish a new release asap.

Thanks,
Lefteris

**Comment by lefterisnik** [comment]
The [fix](https://pypi.python.org/packages/f7/a2/5e6dae6a27ba9f443c197cc691943d768dbb22e9d0ccdd1bf98a27f1b9c2/django-admin-view-permission-1.4.tar.gz#md5=69c00a3b830d6686f000ebb33c213395) has been released.
