### ISSUE TITLE
KeyError in admin using add user

### ISSUE THREAD

**Issue by fredysqm** [ctxis/django-admin-view-permission#47]
In admin, when using a add user model form raises a key error:

```
Request Method: | GET
http://127.0.0.1:8000/admin/auth/user/add/
KeyError: 'password'
```

**Comment by lefterisnik** [comment]
Hi @fredysqm, 

This issue has been fixed on #43 and it has been included on django-admin-view-permission 1.6 release.

Thanks,
Lefteris
