### ISSUE TITLE
Apply permissions to Customized AdminSite classes

### ISSUE THREAD

**Issue by melaku-z** [ctxis/django-admin-view-permission#51]
The permissions apply to django.contrib.admin.site.
Admn sites that subclass AdminSite and override some properties cannot have the view functionality.

**Comment by RuiPedroLeal** [comment]
Well, i'm very new to Django (although a long time Rails, NodeJS and Java guy) but i was actually facing this problem for the last hour. I subclassed an AdminSite during the morning and after the launch detected the admin_view_permission was not working. 

I managed to solve this by doing the below (although not sure if this is the right way):

```
import admin_view_permission
...
#class MyAdminSite(admin.AdminSite)
class MyAdminSite(admin_view_permission.admin.AdminViewPermissionAdminSite):

```

Appears to be working ok now!

**Comment by melaku-z** [comment]
Yes, RuiPedroLeal's code worked for me to (Thank you very much). If this is the write way, maybe it should be added to the docs.
