### ISSUE TITLE
Users with "change" permissions see "delete selected"  action in drop down

### ISSUE THREAD

**Issue by Anton-Shutik** [ctxis/django-admin-view-permission#56]
Users with "change" permissions see "delete selected"  action in drop down. When they submit this action, they get 403 error, but I think they should not even see it.

**Comment by Anton-Shutik** [comment]
I made a fix [here](https://github.com/ctxis/django-admin-view-permission/pull/57)
@lefterisnik take a look pls

**Comment by lefterisnik** [comment]
Closed by #57
