### ISSUE TITLE
Request to reference your app

### ISSUE THREAD

**Issue by monk8800** [ctxis/django-admin-view-permission#7]
Hi guys, i was looking around the django packages site if there was any way to add view permissions, then i came across your app. Am looking to create a youtube tutorial around your app and just wanted to reach out to you guys if its ok to reference your app in the event it meets my needs of cause full credit goes to you guys the authors.

**Comment by orf** [comment]
Its perfectly fine to reference this module wherever you like :+1:

**Comment by monk8800** [comment]
Thanks

**Comment by orf** [comment]
Also please post a link here when your finished :)

**Comment by monk8800** [comment]
@orf  here is the tutorial, https://www.youtube.com/watch?v=f6Doj2LOIlo&t=286s
