### ISSUE TITLE
View permission with custom permissions

### ISSUE THREAD

**Issue by savaskoc** [ctxis/django-admin-view-permission#8]
Hi,

This package override models' meta permissions attribute so any custom permissions will not apply.

It would be nice that the view permission is added to permissions attribute rather than overridden.

**Comment by lefterisnik** [comment]
Hi @savaskoc,

Thanks for the reporting. Sorry for the short delay. I pushed a branch which fixes the problem. Could you check it out? 

I will merge this on master on few days.

Thanks,
lefteris
